POST {{host}}/a/list
Authorization: {{auth}}
Content-Type: application/json;charset=UTF-8
User-Agent: {{agent}}

{"pageNo":1,"pageSize":2,"prefix":"","sort":[{"key":"code","order":"DESC"}],"where":[]}


###
GET {{host}}/a/view
Authorization: {{auth}}
Content-Type: application/json;charset=UTF-8
User-Agent: {{agent}}
